spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: admin@123456
    url: jdbc:mysql://39.108.115.173/ebaychain_db?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 127.0.0.1
    port: 6379
server:
  context-path: /sell

wechat:
  mpAppId: wx3e3245c32dee0955
  mpAppSecret: bc36afbb4889e12e980ccab378e24a08
  openAppId: wx3e3245c32dee0955
  openAppSecret: bc36afbb4889e12e980ccab378e24a08
  mchId: 1490489662
  mchKey: vnd4IWMO9tE5WiMOCL6H0r8REJowVasU
  keyPath: /var/weixin_cert/apiclient_cert.p12
  notifyUrl: http://www.wstsoftware.com/sell/pay/notify
  templateId:
    orderStatus: e-Cqq67QxD6YNI41iRiqawEYdFavW_7pc7LyEMb-yeQ

projectUrl:
  wechatMpAuthorize: http://www.wstsoftware.com
  wechatOpenAuthorize: http://www.wstsoftware.com
  sell: http://www.wstsoftware.com

ebay:
  tokenUrl: https://api.ebay.com/identity/v1/oauth2/token
  authorization: Basic LWx5c2hvcGluLVBSRC0yNWQ4NjUyODMtNzA4YWVkZGY6UFJELTVkODY1MjgzN2JmNy1lNzMzLTRlZmMtYjA0YS1hMWI3
  redirectUri: _--lyshopin-PRD-2-vzitsrs
  itemUrl: https://api.ebay.com/buy/browse/v1/item/
  itemGroupUrl: https://api.ebay.com/buy/browse/v1/item/get_items_by_item_group?item_group_id=

scheduled:
  distributionCron: 3 * * * * ?

winitTracking:
trackUrl: http://202.170.134.65:8180/oso-api/service
logisticsAppKey: 2006fengshangfei@163.com
logisticsToken: AgAAAA**AQAAAA**aAAAAA**B1/cWQ**nY+sHZ2PrBmdj6wVnY+sEZ2PrA2dj6ACl4SpDZWKpQidj6x9nY+seQ**2UUDAA**AAMAAA**0PQ3N17rsJjnEEzYDvhfWtPmGyDbVhAQV4/qUA8xJ9Xpt6pRsB/OP1RYHLdVMugr5PMxOwEoKxj2KCCHw+LPiXRo46/bzVRCUFP9EtouMJDgV+jSExRP+AdDY6jJ+jUaR5ttw2JZbhXKSE82YzvQaIXaGdbP4UkO6yPbjj+kfuWJOfjF16i7h7fvSKJYeGlss+8B5YOR33NBimE18GeGbRTjE+zvcaHswTnhhWkAbcqi1A36t8pFeJAJH7VYCIq80/+EeAWgW3R3EG+dX7caxK+Vs7ji4W6lsm+pPBrjPv78jRlVzs1AwHnddRkERHgwqZWBRP1PFvzKjRtX3E9yUkOHFVNJXrYgKJmsYRhYt+UABt4oYqXA/uOf07u/irsNr/05j61zIHlyayk+sYDvPNM+fUL5K78rxnGm6IvlH+5Zd70p15DZLeSVNMEp8aPy3AbY67FsRFJxAOeYzVtwizPnEWVmEBO/PkD80fDnNbceUsbBEX9rdj1oqekzEKk2MV/F9vtJaadV2v4J5pfke+peNz5cQixmmeyJVhN5z6Dz4r9iy7qlijcSoVXpyNmuB4KZKi05nhlnxq1XBeLOFE+aeLgvB2HkOX2yqO95ovYrmCTAjAIkuslyuk7Q1v55uuXS1SOqu/fmvLL1JDFtTIZiioCyHCOFnLBuFpC28xXJBmmOsV6EZ/U7AqiLo3bAEYtLKydsS/cT+QIIfHDiDKOlGDFj2hLPPmHg61PD3CP1x4L/4WduF7caENUN+DT+

oss:
  endPoint: oss-cn-shenzhen.aliyuncs.com
  accessKeyId: LTAI4ZZnKNNlkvVz
  accessKeySecret: yaLNWDopT70aT2YCIWv7OPczEa1gh7
  backetName: sellers
  folder: images