spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Abcd1234root
    url: jdbc:mysql://182.92.157.1/ebaychain_db?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 127.0.0.1
    port: 6379
server:
  context-path: /sell
  port: 8080
#logging:
#  pattern:
#    console: "%d - %msg%n"
#  path: /var/log/tomcat/
#  file: /var/log/tomcat/sell.log
#  level:
#    com.winit.LoggerTest: debug

wechat:
  mpAppId: wx7b2ea819030c5b48
  mpAppSecret: 3a7fea7716666bc142b97fbd8ce7c078
  openAppId: wx7b2ea819030c5b48
  openAppSecret: 3a7fea7716666bc142b97fbd8ce7c078
  mchId: 1483469312
  mchKey: 06C56A89949D617xxxxxxxxxxx
  keyPath: /var/weixin_cert/h5.p12
  notifyUrl: http://fks3989.free.ngrok.cc/sell/pay/notify
  templateId:
    orderStatus: e-Cqq67QxD6YNI41iRiqawEYdFavW_7pc7LyEMb-yeQ

projectUrl:
  wechatMpAuthorize: http://fks3989.free.ngrok.cc
  wechatOpenAuthorize: http://fks3989.free.ngrok.cc
  sell: http://fks3989.free.ngrok.cc

ebay:
  tokenUrl: https://api.ebay.com/identity/v1/oauth2/token
  authorization: Basic LWx5c2hvcGluLVBSRC0yNWQ4NjUyODMtNzA4YWVkZGY6UFJELTVkODY1MjgzN2JmNy1lNzMzLTRlZmMtYjA0YS1hMWI3
  redirectUri: _--lyshopin-PRD-2-vzitsrs
  itemUrl: https://api.ebay.com/buy/browse/v1/item/
  itemGroupUrl: https://api.ebay.com/buy/browse/v1/item/get_items_by_item_group?item_group_id=

scheduled:
  distributionCron: 3 * * * * ?

winitTracking:
trackUrl: http://202.170.134.65:8180/oso-api/service
logisticsAppKey: 2006fengshangfei@163.com
logisticsToken: AgAAAA**AQAAAA**aAAAAA**B1/cWQ**nY+sHZ2PrBmdj6wVnY+sEZ2PrA2dj6ACl4SpDZWKpQidj6x9nY+seQ**2UUDAA**AAMAAA**0PQ3N17rsJjnEEzYDvhfWtPmGyDbVhAQV4/qUA8xJ9Xpt6pRsB/OP1RYHLdVMugr5PMxOwEoKxj2KCCHw+LPiXRo46/bzVRCUFP9EtouMJDgV+jSExRP+AdDY6jJ+jUaR5ttw2JZbhXKSE82YzvQaIXaGdbP4UkO6yPbjj+kfuWJOfjF16i7h7fvSKJYeGlss+8B5YOR33NBimE18GeGbRTjE+zvcaHswTnhhWkAbcqi1A36t8pFeJAJH7VYCIq80/+EeAWgW3R3EG+dX7caxK+Vs7ji4W6lsm+pPBrjPv78jRlVzs1AwHnddRkERHgwqZWBRP1PFvzKjRtX3E9yUkOHFVNJXrYgKJmsYRhYt+UABt4oYqXA/uOf07u/irsNr/05j61zIHlyayk+sYDvPNM+fUL5K78rxnGm6IvlH+5Zd70p15DZLeSVNMEp8aPy3AbY67FsRFJxAOeYzVtwizPnEWVmEBO/PkD80fDnNbceUsbBEX9rdj1oqekzEKk2MV/F9vtJaadV2v4J5pfke+peNz5cQixmmeyJVhN5z6Dz4r9iy7qlijcSoVXpyNmuB4KZKi05nhlnxq1XBeLOFE+aeLgvB2HkOX2yqO95ovYrmCTAjAIkuslyuk7Q1v55uuXS1SOqu/fmvLL1JDFtTIZiioCyHCOFnLBuFpC28xXJBmmOsV6EZ/U7AqiLo3bAEYtLKydsS/cT+QIIfHDiDKOlGDFj2hLPPmHg61PD3CP1x4L/4WduF7caENUN+DT+

oss:
  endPoint: oss-cn-shenzhen.aliyuncs.com
  accessKeyId: LTAI4ZZnKNNlkvVz
  accessKeySecret: yaLNWDopT70aT2YCIWv7OPczEa1gh7
  backetName: sellers
  folder: images